language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main'
  - sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'
  - sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'
  # To have an up-to-date valgrind (>=3.8 required)
  - sudo add-apt-repository -y 'deb http://ppa.launchpad.net/danmbox/ppa/ubuntu precise main'
  - sudo apt-get update -qq
install:
  # Always install latest GCC 4.8 to avoid bugs in old STL when compiling with Clang.
  - sudo apt-get install -qq --force-yes g++-4.8
  - sudo apt-get install -qq --force-yes valgrind ${COMPILER_TO_INSTALL}

script: CXX=${COMPILER_TO_RUN} ./postsubmit.sh

branches:
  only:
    - master

matrix:
  include:
    - compiler: gcc
      env: COMPILER_TO_INSTALL=g++-4.8     COMPILER_TO_RUN=g++-4.8
    - compiler: gcc
      env: COMPILER_TO_INSTALL=g++-4.9     COMPILER_TO_RUN=g++-4.9
    - compiler: gcc
      env: COMPILER_TO_INSTALL=g++-5       COMPILER_TO_RUN=g++-5
    - compiler: clang
      env: COMPILER_TO_INSTALL=clang++-3.4 COMPILER_TO_RUN=clang++
    - compiler: clang
      env: COMPILER_TO_INSTALL=clang++-3.5 COMPILER_TO_RUN=clang++-3.5
    - compiler: clang
      env: COMPILER_TO_INSTALL=clang++-3.6 COMPILER_TO_RUN=clang++-3.6
    - compiler: clang
      env: COMPILER_TO_INSTALL=clang++-3.7 COMPILER_TO_RUN=clang++-3.7
