branches:
  only:
  - master
dist: trusty
language: cpp
matrix:
  fast_finish: true
  include:
  - compiler: gcc
    env: UBUNTU=16.04 COMPILER=gcc-6
    install: extras/scripts/travis_ci_install_linux.sh
    os: linux
    script: extras/scripts/postsubmit.sh DebugValgrind
  - compiler: gcc
    env: UBUNTU=16.04 COMPILER=gcc-6
    install: extras/scripts/travis_ci_install_linux.sh
    os: linux
    script: extras/scripts/postsubmit.sh ReleaseValgrind
  - compiler: gcc
    env: UBUNTU=16.04 COMPILER=gcc-6
    install: extras/scripts/travis_ci_install_linux.sh
    os: linux
    script: extras/scripts/postsubmit.sh DebugAsanUbsan
  - compiler: gcc
    env: UBUNTU=16.04 COMPILER=gcc-5
    install: extras/scripts/travis_ci_install_linux.sh
    os: linux
    script: extras/scripts/postsubmit.sh DebugValgrind
  - compiler: gcc
    env: UBUNTU=16.04 COMPILER=gcc-5
    install: extras/scripts/travis_ci_install_linux.sh
    os: linux
    script: extras/scripts/postsubmit.sh ReleaseValgrind
  - compiler: gcc
    env: UBUNTU=16.04 COMPILER=gcc-5
    install: extras/scripts/travis_ci_install_linux.sh
    os: linux
    script: extras/scripts/postsubmit.sh DebugAsanUbsan
  - compiler: clang
    env: UBUNTU=16.04 COMPILER=clang-3.8 STL=libstdc++
    install: extras/scripts/travis_ci_install_linux.sh
    os: linux
    script: extras/scripts/postsubmit.sh DebugValgrind
  - compiler: clang
    env: UBUNTU=16.04 COMPILER=clang-3.8 STL=libstdc++
    install: extras/scripts/travis_ci_install_linux.sh
    os: linux
    script: extras/scripts/postsubmit.sh ReleaseValgrind
  - compiler: clang
    env: UBUNTU=16.04 COMPILER=clang-3.8 STL=libstdc++
    install: extras/scripts/travis_ci_install_linux.sh
    os: linux
    script: extras/scripts/postsubmit.sh DebugAsanUbsan
  - compiler: gcc
    env: UBUNTU=15.10 COMPILER=bazel
    install: extras/scripts/travis_ci_install_linux.sh
    os: linux
    script: extras/scripts/postsubmit.sh DebugPlain
  - compiler: gcc
    env: COMPILER=gcc-4.8
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    script: extras/scripts/postsubmit.sh DebugValgrind
  - compiler: gcc
    env: COMPILER=gcc-4.8
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    script: extras/scripts/postsubmit.sh ReleaseValgrind
  - compiler: gcc
    env: COMPILER=gcc-5
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    script: extras/scripts/postsubmit.sh DebugValgrind
  - compiler: gcc
    env: COMPILER=gcc-5
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    script: extras/scripts/postsubmit.sh ReleaseValgrind
  - compiler: gcc
    env: COMPILER=gcc-5
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    script: extras/scripts/postsubmit.sh DebugAsanUbsan
  - compiler: clang
    env: COMPILER=clang-3.6 STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    script: extras/scripts/postsubmit.sh DebugValgrind
  - compiler: clang
    env: COMPILER=clang-3.6 STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    script: extras/scripts/postsubmit.sh ReleaseValgrind
  - compiler: clang
    env: COMPILER=clang-3.7 STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    script: extras/scripts/postsubmit.sh DebugValgrind
  - compiler: clang
    env: COMPILER=clang-3.7 STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    script: extras/scripts/postsubmit.sh ReleaseValgrind
  - compiler: clang
    env: COMPILER=clang-3.8 STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    script: extras/scripts/postsubmit.sh DebugValgrind
  - compiler: clang
    env: COMPILER=clang-3.8 STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    script: extras/scripts/postsubmit.sh ReleaseValgrind
  - compiler: clang
    env: COMPILER=clang-3.8 STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    script: extras/scripts/postsubmit.sh DebugAsanUbsan
  - compiler: clang
    env: COMPILER=clang-default STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    osx_image: xcode7.1
    script: extras/scripts/postsubmit.sh DebugValgrind
  - compiler: clang
    env: COMPILER=clang-default STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    osx_image: xcode7.1
    script: extras/scripts/postsubmit.sh ReleaseValgrind
  - compiler: clang
    env: COMPILER=clang-default STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    osx_image: xcode7.1
    script: extras/scripts/postsubmit.sh DebugAsan
  - compiler: clang
    env: COMPILER=clang-default STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    osx_image: xcode7.3
    script: extras/scripts/postsubmit.sh DebugValgrind
  - compiler: clang
    env: COMPILER=clang-default STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    osx_image: xcode7.3
    script: extras/scripts/postsubmit.sh ReleaseValgrind
  - compiler: clang
    env: COMPILER=clang-default STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    osx_image: xcode7.3
    script: extras/scripts/postsubmit.sh DebugAsan
  - compiler: clang
    env: COMPILER=clang-default STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    osx_image: xcode8
    script: extras/scripts/postsubmit.sh DebugValgrind
  - compiler: clang
    env: COMPILER=clang-default STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    osx_image: xcode8
    script: extras/scripts/postsubmit.sh ReleaseValgrind
  - compiler: clang
    env: COMPILER=clang-default STL=libc++
    install: extras/scripts/travis_ci_install_osx.sh
    os: osx
    osx_image: xcode8
    script: extras/scripts/postsubmit.sh DebugAsan
services:
- docker
sudo: required

