
language: cpp

compiler:
  - clang
  - gcc

# These install GCC 4.8 and set that as the GCC version to use.
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} && make && cd build/tests && { [[ ${BUILD_TYPE} != "Debug" ]] || ctest --output-on-failure -j4; }

branches:
  only:
    - master

env:
  - BUILD_TYPE=Release CXXFLAGS=-Werror
  - BUILD_TYPE=Debug   CXXFLAGS=-Werror
