sudo: required
dist: trusty
services:
    - docker
language: cpp

install:
    - "if [ ${TRAVIS_OS_NAME} = 'linux' ]; then ./scripts/travis_ci_install_linux.sh; fi"
    - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then ./scripts/travis_ci_install_osx.sh; fi"

script: 
    - export OS="${TRAVIS_OS_NAME}"
    - ': ${NO_ASAN:=0}'
    - ': ${NO_VALGRIND:=0}'
    - 'if (( !$NO_ASAN                )); then ./scripts/postsubmit.sh DebugAsan; fi'
    - 'if (( !$NO_VALGRIND            )); then ./scripts/postsubmit.sh DebugValgrind; fi'
    - 'if (( $NO_ASAN && $NO_VALGRIND )); then ./scripts/postsubmit.sh DebugPlain; fi'
    - 'if (( $NO_VALGRIND             )); then ./scripts/postsubmit.sh ReleasePlain; fi'
    - 'if (( !$NO_VALGRIND            )); then ./scripts/postsubmit.sh ReleaseValgrind; fi'

branches:
  only:
    - master
    - coverity_scan

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Tus3JkSCrpYp75GY58IJEpcWxEO+dmwvLz5c31OkIuTH+/s9ZXnAzZs/G+M2FsmG6tnyRtF/1QuzDPrdO46fYrXlb92YVmNPsK9EpH65+rms7fgPcAz0LtZ7c4ubCdlA7BYh7q/IFF2U8RfW/ujED/Yo8JvoZSX+yDdqWtP1diA="

matrix:
  # Report an error as soon as the first matrix entry fails.
  fast_finish: true
  include:
    # Ubuntu 16.04
    # GCC
    - os: linux
      compiler: gcc
      env: UBUNTU=16.04 COMPILER=gcc-5
      # This enables Coverity Scan. It's not important which build matrix entry has this,
      # any entry will do. We can't put it at global scope because it would try to start
      # a Coverity Scan for each build matrix entry.
      addons:
          coverity_scan:
            project:
              name: ""
              description: "A dependency injection framework for C++"
              notification_email: poletti.marco@gmail.com
              build_command_prepend: "cmake ."
              build_command:   "make -j4"
              branch_pattern: coverity_scan
    # Clang with libstdc++
    - os: linux
      compiler: clang
      env: UBUNTU=16.04 COMPILER=clang-3.8 STL=libstdc++
      
    # Ubuntu 15.10
    # GCC
    - os: linux
      compiler: gcc
      # Asan is disabled because it would fail with an error like:
      # runtime error: member call on null pointer of type 'const struct __lambda26'
      # This issue is fixed in the version of GCC shipped in Ubuntu 16.04.
      env: UBUNTU=15.10 COMPILER=gcc-5 NO_ASAN=1
    # Clang with libstdc++
    - os: linux
      compiler: clang
      env: UBUNTU=15.10 COMPILER=clang-3.6 STL=libstdc++
    - os: linux
      compiler: clang
      env: UBUNTU=15.10 COMPILER=clang-3.8 STL=libstdc++
    # Clang with libc++
    - os: linux
      compiler: clang
      env: UBUNTU=15.10 COMPILER=clang-3.6 STL=libc++
    - os: linux
      compiler: clang
      # Asan is disabled because it would fail with an error like:
      # /usr/include/c++/v1/memory:1554:35: runtime error: null pointer passed as argument 2, which is declared to never be null
      env: UBUNTU=15.10 COMPILER=clang-3.8 STL=libc++ NO_ASAN=1
    
    # Ubuntu 14.04
    # GCC
    - os: linux
      compiler: gcc
      # ASAN (aka '-fsanitize=undefined,address') is not supported in GCC 4.8.
      env: UBUNTU=14.04 COMPILER=gcc-4.8   NO_ASAN=1
    - os: linux
      compiler: gcc
      env: UBUNTU=14.04 COMPILER=gcc-5
    # Clang with libstdc++
    - os: linux
      compiler: clang
      env: UBUNTU=14.04 COMPILER=clang-3.5 STL=libstdc++
    - os: linux
      compiler: clang
      env: UBUNTU=14.04 COMPILER=clang-3.8 STL=libstdc++
    # Clang with libc++
    - os: linux
      compiler: clang
      env: UBUNTU=14.04 COMPILER=clang-3.5 STL=libc++
    - os: linux
      compiler: clang
      # ASAN is disabled because Ubuntu Trusty uses libc++ 1.x that doesn't work
      # with ASAN, it fails with this error:
      # /usr/include/c++/v1/memory:1550:35: runtime error: null pointer passed as argument 2, which is declared to never be null
      env: UBUNTU=14.04 COMPILER=clang-3.8 STL=libc++ NO_ASAN=1
      
    # OS X
    # GCC
    - os: osx
      compiler: gcc
      # ASAN (aka '-fsanitize=undefined,address') is not supported in GCC 4.8.
      env: COMPILER=gcc-4.8   NO_ASAN=1
    - os: osx
      compiler: gcc
      env: COMPILER=gcc-5
    # Clang on OS X (with libc++)
    - os: osx
      compiler: clang      
      # ASAN is disabled because it would hit this error:
      # ld: file not found: [...]/libclang_rt.ubsan_osx.a
      # Not sure if that's a limitation of Clang 3.6 on OS X or just of the brew-provided binaries.
      env: COMPILER=clang-3.6 STL=libc++ NO_ASAN=1
    - os: osx
      compiler: clang
      # ASAN is disabled because it would hit this error:
      # ld: file not found: [...]/libclang_rt.ubsan_osx.a
      # Not sure if that's a limitation of Clang 3.7 on OS X or just of the brew-provided binaries.
      env: COMPILER=clang-3.7 STL=libc++ NO_ASAN=1
    # AppleClang on OS X (with libc++)
    - os: osx
      compiler: clang
      # OS X 10.10
      osx_image: xcode7.1
      # ASAN is disabled because AppleClang does not support -fsanitize=undefined.
      env: COMPILER=clang-default STL=libc++ NO_ASAN=1
    - os: osx
      compiler: clang
      # OS X 10.11
      osx_image: xcode7.3
      # ASAN is disabled because AppleClang does not support -fsanitize=undefined.
      env: COMPILER=clang-default STL=libc++ NO_ASAN=1

# Disabled combinations:
#
#    These fail with "'type_traits' file not found" (the <type_traits> header is missing).
#    - os: osx
#      compiler: gcc
#      env: COMPILER=gcc       MY_CXX=g++         STL=libstdc++
#    - os: osx
#      compiler: clang
#      env: COMPILER=clang     MY_CXX=clang++     STL=libstdc++
#    - os: osx
#      compiler: clang
#      env: COMPILER=clang-3.5 MY_CXX=clang++-3.5 STL=libstdc++ NO_VALGRIND=1
#    - os: osx
#      compiler: clang
#      env: COMPILER=clang-3.6 MY_CXX=clang++-3.6 STL=libstdc++
#
#    The compiler complains that the 2-argument constructor of std::pair is ambiguous, even after
#    adding explicit casts to the exact types of the expected overload.
#    - os: osx
#      compiler: clang
#      env: COMPILER=clang     MY_CXX=clang++     STL=libc++ NO_ASAN=1
#
#    This triggers an assert error in the compiler, with the message:
#    "expected to get called on an inlined function!" [...] function isMSExternInline, file Decl.cpp, line 2647.
#    - os: osx
#      compiler: clang
#      env: COMPILER=clang-3.5 MY_CXX=clang++-3.5 STL=libc++ NO_VALGRIND=1 NO_ASAN=1
#
#    This fails with this error:
#       /usr/include/c++/v1/string:1938:44: error: 'basic_string<_CharT, _Traits, _Allocator>' is missing
#       exception specification 'noexcept(is_nothrow_copy_constructible<allocator_type>::value)'
#    TODO: Try again every once in a while (to re-enable these once the bug in libc++ is fixed).
#    - os: linux
#      compiler: clang
#      env: UBUNTU=16.04 COMPILER=clang-3.8 STL=libc++ NO_ASAN=1
